swagger: "2.0"

info:
  version: 1.0.0
  title: Count Dracula
  description: |
    SS (Stupid Simple) API that returns the count of the things requested.

paths:
  /{thing}:
    get:
      summary: Returns the amount of times it was requested.
      description: The increment is based on past requests plus the current request.
      produces:
      - "application/json"
      parameters:
      - name: "thing"
        in: "path"
        description: "Thing to store and count"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"

definitions:
  ApiResponse:
    type: "object"
    properties:
      total:
        type: "integer"
        format: "int32"
